name: HerobrineAIReborn
main: org.jakub1221.herobrineai.HerobrineAI
version: 3.4.3
description: Let Herobrine haunt u!
commands:
    hb-ai:
      description: Main command.
      usage: /hb-ai help
    hb:
      description: Main command.
      usage: /hb help