name: HerobrineAIReborn
main: org.jakub1221.herobrineai.HerobrineAI
version: 4.0
description: Let Herobrine haunt u!
load: POSTWORLD
api-version: '1.20'
commands:
    hb-ai:
      description: Main command.
      usage: /hb-ai help
    hb:
      description: Main command.
      usage: /hb help